K_epochs: 1
action_dim: 9
att_dim_k: 128
att_dim_v: 128
att_n_heads: 8
att_output_dim: 128
depth: 3
embedding_dim: 128
entropy_coef: 0.05
epsilon: 0.05
eval_per_step: 5000
evaluate_times: 2
evaluator_device: cpu
fcra_aggregator: mean
gamma: 0.99
gnn_output_dim: 128
lamda: 0.95
learner_device: cuda
lr: 0.0005
max_train_steps: 200000000
mlp_hidden_dim: 128
num_attacker: 1
num_defender: 10
num_layers: 2
num_relation: 3
pretrain_model_cwd: ./pretrain/experiment/pretrain_model_15
rnn_hidden_dim: 128
sample_epi_num: 1
save_cwd: ./model
save_gap: 100000
semantic_level_aggregator: mean
set_adam_eps: true
state_dim: 4
use_adv_norm: true
use_agent_specific: true
use_grad_clip: true
use_lr_decay: true
use_orthogonal_init: true
use_reward_norm: true
use_spectral_norm: true
use_value_clip: true
vertex_level_aggregator: mean
worker_device: cpu
